git:
  baseurl: https://github.com
  prefix: qubesos/qubes-
  branch: main
  maintainers:
    # marmarek
    - '0064428F455451B3EBE78A7F063938BA42CFA724'
    # simon
    - '274E12AB03F2FE293765FC06DA0434BC706E1FCF'

backend-vmm: xen
debug: true
verbose: true
qubes-release: r4.2

distributions:
  - vm-jammy
  - vm-noble

templates:
  # Using packages_jammy.list + gnome directory
  - jammy:
      dist: jammy
      flavor: gnome
  # Using packages_jammy.list only (no gnome apps)
  - jammy-standard:
      dist: jammy
  # Using packages_jammy_minimal.list
  - jammy-minimal:
      dist: jammy
      flavor: minimal
  # Using packages_noble.list + gnome directory
  - noble:
      dist: noble
      flavor: gnome
  # Using packages_noble.list only (no gnome apps)
  - noble-standard:
      dist: noble
  # Using packages_noble_minimal.list
  - noble-minimal:
      dist: noble
      flavor: minimal

components:
  - builderv2:
      packages: False
      branch: main
  - builder-debian:
      packages: False
  - vmm-xen-guest
  - core-vchan-xen
  - core-qubesdb
  - core-qrexec
  - linux-utils
  - core-agent-linux
  - gui-common
  - gui-agent-linux
  - app-linux-split-gpg
  - app-linux-input-proxy
  - app-linux-usb-proxy
  - app-linux-pdf-converter
  - app-linux-img-converter
  - mgmt-salt
  - fwupd
  - repo-templates
  - meta-packages
  - salt

executor:
 type: docker
 options:
   image: "qubes-builder-ubuntu:latest"

stages:
  - fetch
  - prep
  - build

